export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_REQUEST_SUCCESS = 'GET_ARTICLES_REQUEST_SUCCESS';
export const GET_ARTICLES_REQUEST_FAILURE = 'GET_ARTICLES_REQUEST_FAILURE';

export const CHANGE_ARTICLE_TITLE_REQUEST = 'CHANGE_ARTICLE_TITLE_REQUEST';
export const CHANGE_ARTICLE_TITLE_SUCCESS = 'CHANGE_ARTICLE_TITLE_SUCCESS';
export const CHANGE_ARTICLE_TITLE_FAILURE = 'CHANGE_ARTICLE_TITLE_FAILURE';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_REQUEST_SUCCESS = 'DELETE_ARTICLE_REQUEST_SUCCESS';
export const DELETE_ARTICLE_REQUEST_FAILURE = 'DELETE_ARTICLE_REQUEST_FAILURE';
